### ISSUE TITLE
[BUG] Linux installation not working on ARM

### ISSUE THREAD

**Issue by jackokring** [GuardKenzie/chafa.py#16]
```
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      Traceback (most recent call last):
        File "/home/jackokring/www/venv/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/jackokring/www/venv/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/jackokring/www/venv/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "/tmp/pip-build-env-v4xz00bh/overlay/lib/python3.9/site-packages/hatchling/build.py", line 56, in build_wheel
          return os.path.basename(next(builder.build(wheel_directory, ['standard'])))
        File "/tmp/pip-build-env-v4xz00bh/overlay/lib/python3.9/site-packages/hatchling/builders/plugin/interface.py", line 150, in build
          build_hook.initialize(version, build_data)
        File "/tmp/pip-install-hepyeps1/chafa-py_f4eb9f5b69f1489b8dfc24f128d88ea6/hatch_build.py", line 22, in initialize
          raise FileNotFoundError("No file matched the glob pattern 'libs/linux/*chafa*.dll'")
      FileNotFoundError: No file matched the glob pattern 'libs/linux/*chafa*.dll'
      [end of output]
```
When updating all packages.

**Comment by GuardKenzie** [comment]
Are you using pip to manage your python packages?

Can you provide the command that produced this output?

**Comment by jackokring** [comment]
```
(venv) jackokring@penguin:~/www$ pip install chafa.py
Collecting chafa.py
  Using cached chafa.py-1.0.2.tar.gz (3.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      Traceback (most recent call last):
        File "/home/jackokring/www/venv/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/jackokring/www/venv/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/jackokring/www/venv/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "/tmp/pip-build-env-_g88986m/overlay/lib/python3.9/site-packages/hatchling/build.py", line 56, in build_wheel
          return os.path.basename(next(builder.build(wheel_directory, ['standard'])))
        File "/tmp/pip-build-env-_g88986m/overlay/lib/python3.9/site-packages/hatchling/builders/plugin/interface.py", line 150, in build
          build_hook.initialize(version, build_data)
        File "/tmp/pip-install-90sx97lk/chafa-py_abf2a125a22c4702a454efbb95f259cb/hatch_build.py", line 22, in initialize
          raise FileNotFoundError("No file matched the glob pattern 'libs/linux/*chafa*.dll'")
      FileNotFoundError: No file matched the glob pattern 'libs/linux/*chafa*.dll'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.```

**Comment by GuardKenzie** [comment]
Looks like pip is attempting to build from source. Building the source distribution through pip is currently unsupported (I need to figure out how to handle building C libraries with hatchling) but I was under the impression that I was providing a built wheel for all Linux distros.

Which python version are you on and what are your supported platform tags? (you can get those via `pip debug --verbose`)

**Comment by GuardKenzie** [comment]
I have made building from source possible again, provided you have the chafa and glib libraries installed and somewhere on your path. This will be implemented in the next minor version.

I am however interested in why pip isn't installing chafa.py via wheel so could you still provide me with the details I asked for above?

**Comment by jackokring** [comment]
```
venv) jackokring@penguin:~/www$ pip debug --verbose
WARNING: This command is only meant for debugging. Do not use this with automation for parsing and getting these details, since the output and options of this command may change without notice.
pip version: pip 23.0 from /home/jackokring/www/venv/lib/python3.9/site-packages/pip (python 3.9)
sys.version: 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110]
sys.executable: /home/jackokring/www/venv/bin/python3
sys.getdefaultencoding: utf-8
sys.getfilesystemencoding: utf-8
locale.getpreferredencoding: UTF-8
sys.platform: linux
sys.implementation:
  name: cpython
'cert' config value: Not specified
REQUESTS_CA_BUNDLE: None
CURL_CA_BUNDLE: None
pip._vendor.certifi.where(): /home/jackokring/www/venv/lib/python3.9/site-packages/pip/_vendor/certifi/cacert.pem
pip._vendor.DEBUNDLED: False
vendored library versions:
  CacheControl==0.12.11
  colorama==0.4.6
  distlib==0.3.6
  distro==1.8.0
  msgpack==1.0.4
  packaging==21.3
  platformdirs==2.6.2
  pyparsing==3.0.9
  pyproject-hooks==1.0.0
  requests==2.28.2
  certifi==2022.12.07
  chardet==5.1.0
  idna==3.4
  urllib3==1.26.14
  rich==12.6.0 (Unable to locate actual module version, using vendor.txt specified version)
  pygments==2.13.0
  typing_extensions==4.4.0 (Unable to locate actual module version, using vendor.txt specified version)
  resolvelib==0.8.1
  setuptools==44.0.0 (Unable to locate actual module version, using vendor.txt specified version)
  six==1.16.0
  tenacity==8.1.0 (Unable to locate actual module version, using vendor.txt specified version)
  tomli==2.0.1
  webencodings==0.5.1 (Unable to locate actual module version, using vendor.txt specified version)
Compatible tags: 369
  cp39-cp39-manylinux_2_31_aarch64
  cp39-cp39-manylinux_2_30_aarch64
  cp39-cp39-manylinux_2_29_aarch64
  cp39-cp39-manylinux_2_28_aarch64
  cp39-cp39-manylinux_2_27_aarch64
  cp39-cp39-manylinux_2_26_aarch64
  cp39-cp39-manylinux_2_25_aarch64
  cp39-cp39-manylinux_2_24_aarch64
  cp39-cp39-manylinux_2_23_aarch64
  cp39-cp39-manylinux_2_22_aarch64
  cp39-cp39-manylinux_2_21_aarch64
  cp39-cp39-manylinux_2_20_aarch64
  cp39-cp39-manylinux_2_19_aarch64
  cp39-cp39-manylinux_2_18_aarch64
  cp39-cp39-manylinux_2_17_aarch64
  cp39-cp39-manylinux2014_aarch64
  cp39-cp39-linux_aarch64
  cp39-abi3-manylinux_2_31_aarch64
  cp39-abi3-manylinux_2_30_aarch64
  cp39-abi3-manylinux_2_29_aarch64
  cp39-abi3-manylinux_2_28_aarch64
  cp39-abi3-manylinux_2_27_aarch64
  cp39-abi3-manylinux_2_26_aarch64
  cp39-abi3-manylinux_2_25_aarch64
  cp39-abi3-manylinux_2_24_aarch64
  cp39-abi3-manylinux_2_23_aarch64
  cp39-abi3-manylinux_2_22_aarch64
  cp39-abi3-manylinux_2_21_aarch64
  cp39-abi3-manylinux_2_20_aarch64
  cp39-abi3-manylinux_2_19_aarch64
  cp39-abi3-manylinux_2_18_aarch64
  cp39-abi3-manylinux_2_17_aarch64
  cp39-abi3-manylinux2014_aarch64
  cp39-abi3-linux_aarch64
  cp39-none-manylinux_2_31_aarch64
  cp39-none-manylinux_2_30_aarch64
  cp39-none-manylinux_2_29_aarch64
  cp39-none-manylinux_2_28_aarch64
  cp39-none-manylinux_2_27_aarch64
  cp39-none-manylinux_2_26_aarch64
  cp39-none-manylinux_2_25_aarch64
  cp39-none-manylinux_2_24_aarch64
  cp39-none-manylinux_2_23_aarch64
  cp39-none-manylinux_2_22_aarch64
  cp39-none-manylinux_2_21_aarch64
  cp39-none-manylinux_2_20_aarch64
  cp39-none-manylinux_2_19_aarch64
  cp39-none-manylinux_2_18_aarch64
  cp39-none-manylinux_2_17_aarch64
  cp39-none-manylinux2014_aarch64
  cp39-none-linux_aarch64
  cp38-abi3-manylinux_2_31_aarch64
  cp38-abi3-manylinux_2_30_aarch64
  cp38-abi3-manylinux_2_29_aarch64
  cp38-abi3-manylinux_2_28_aarch64
  cp38-abi3-manylinux_2_27_aarch64
  cp38-abi3-manylinux_2_26_aarch64
  cp38-abi3-manylinux_2_25_aarch64
  cp38-abi3-manylinux_2_24_aarch64
  cp38-abi3-manylinux_2_23_aarch64
  cp38-abi3-manylinux_2_22_aarch64
  cp38-abi3-manylinux_2_21_aarch64
  cp38-abi3-manylinux_2_20_aarch64
  cp38-abi3-manylinux_2_19_aarch64
  cp38-abi3-manylinux_2_18_aarch64
  cp38-abi3-manylinux_2_17_aarch64
  cp38-abi3-manylinux2014_aarch64
  cp38-abi3-linux_aarch64
  cp37-abi3-manylinux_2_31_aarch64
  cp37-abi3-manylinux_2_30_aarch64
  cp37-abi3-manylinux_2_29_aarch64
  cp37-abi3-manylinux_2_28_aarch64
  cp37-abi3-manylinux_2_27_aarch64
  cp37-abi3-manylinux_2_26_aarch64
  cp37-abi3-manylinux_2_25_aarch64
  cp37-abi3-manylinux_2_24_aarch64
  cp37-abi3-manylinux_2_23_aarch64
  cp37-abi3-manylinux_2_22_aarch64
  cp37-abi3-manylinux_2_21_aarch64
  cp37-abi3-manylinux_2_20_aarch64
  cp37-abi3-manylinux_2_19_aarch64
  cp37-abi3-manylinux_2_18_aarch64
  cp37-abi3-manylinux_2_17_aarch64
  cp37-abi3-manylinux2014_aarch64
  cp37-abi3-linux_aarch64
  cp36-abi3-manylinux_2_31_aarch64
  cp36-abi3-manylinux_2_30_aarch64
  cp36-abi3-manylinux_2_29_aarch64
  cp36-abi3-manylinux_2_28_aarch64
  cp36-abi3-manylinux_2_27_aarch64
  cp36-abi3-manylinux_2_26_aarch64
  cp36-abi3-manylinux_2_25_aarch64
  cp36-abi3-manylinux_2_24_aarch64
  cp36-abi3-manylinux_2_23_aarch64
  cp36-abi3-manylinux_2_22_aarch64
  cp36-abi3-manylinux_2_21_aarch64
  cp36-abi3-manylinux_2_20_aarch64
  cp36-abi3-manylinux_2_19_aarch64
  cp36-abi3-manylinux_2_18_aarch64
  cp36-abi3-manylinux_2_17_aarch64
  cp36-abi3-manylinux2014_aarch64
  cp36-abi3-linux_aarch64
  cp35-abi3-manylinux_2_31_aarch64
  cp35-abi3-manylinux_2_30_aarch64
  cp35-abi3-manylinux_2_29_aarch64
  cp35-abi3-manylinux_2_28_aarch64
  cp35-abi3-manylinux_2_27_aarch64
  cp35-abi3-manylinux_2_26_aarch64
  cp35-abi3-manylinux_2_25_aarch64
  cp35-abi3-manylinux_2_24_aarch64
  cp35-abi3-manylinux_2_23_aarch64
  cp35-abi3-manylinux_2_22_aarch64
  cp35-abi3-manylinux_2_21_aarch64
  cp35-abi3-manylinux_2_20_aarch64
  cp35-abi3-manylinux_2_19_aarch64
  cp35-abi3-manylinux_2_18_aarch64
  cp35-abi3-manylinux_2_17_aarch64
  cp35-abi3-manylinux2014_aarch64
  cp35-abi3-linux_aarch64
  cp34-abi3-manylinux_2_31_aarch64
  cp34-abi3-manylinux_2_30_aarch64
  cp34-abi3-manylinux_2_29_aarch64
  cp34-abi3-manylinux_2_28_aarch64
  cp34-abi3-manylinux_2_27_aarch64
  cp34-abi3-manylinux_2_26_aarch64
  cp34-abi3-manylinux_2_25_aarch64
  cp34-abi3-manylinux_2_24_aarch64
  cp34-abi3-manylinux_2_23_aarch64
  cp34-abi3-manylinux_2_22_aarch64
  cp34-abi3-manylinux_2_21_aarch64
  cp34-abi3-manylinux_2_20_aarch64
  cp34-abi3-manylinux_2_19_aarch64
  cp34-abi3-manylinux_2_18_aarch64
  cp34-abi3-manylinux_2_17_aarch64
  cp34-abi3-manylinux2014_aarch64
  cp34-abi3-linux_aarch64
  cp33-abi3-manylinux_2_31_aarch64
  cp33-abi3-manylinux_2_30_aarch64
  cp33-abi3-manylinux_2_29_aarch64
  cp33-abi3-manylinux_2_28_aarch64
  cp33-abi3-manylinux_2_27_aarch64
  cp33-abi3-manylinux_2_26_aarch64
  cp33-abi3-manylinux_2_25_aarch64
  cp33-abi3-manylinux_2_24_aarch64
  cp33-abi3-manylinux_2_23_aarch64
  cp33-abi3-manylinux_2_22_aarch64
  cp33-abi3-manylinux_2_21_aarch64
  cp33-abi3-manylinux_2_20_aarch64
  cp33-abi3-manylinux_2_19_aarch64
  cp33-abi3-manylinux_2_18_aarch64
  cp33-abi3-manylinux_2_17_aarch64
  cp33-abi3-manylinux2014_aarch64
  cp33-abi3-linux_aarch64
  cp32-abi3-manylinux_2_31_aarch64
  cp32-abi3-manylinux_2_30_aarch64
  cp32-abi3-manylinux_2_29_aarch64
  cp32-abi3-manylinux_2_28_aarch64
  cp32-abi3-manylinux_2_27_aarch64
  cp32-abi3-manylinux_2_26_aarch64
  cp32-abi3-manylinux_2_25_aarch64
  cp32-abi3-manylinux_2_24_aarch64
  cp32-abi3-manylinux_2_23_aarch64
  cp32-abi3-manylinux_2_22_aarch64
  cp32-abi3-manylinux_2_21_aarch64
  cp32-abi3-manylinux_2_20_aarch64
  cp32-abi3-manylinux_2_19_aarch64
  cp32-abi3-manylinux_2_18_aarch64
  cp32-abi3-manylinux_2_17_aarch64
  cp32-abi3-manylinux2014_aarch64
  cp32-abi3-linux_aarch64
  py39-none-manylinux_2_31_aarch64
  py39-none-manylinux_2_30_aarch64
  py39-none-manylinux_2_29_aarch64
  py39-none-manylinux_2_28_aarch64
  py39-none-manylinux_2_27_aarch64
  py39-none-manylinux_2_26_aarch64
  py39-none-manylinux_2_25_aarch64
  py39-none-manylinux_2_24_aarch64
  py39-none-manylinux_2_23_aarch64
  py39-none-manylinux_2_22_aarch64
  py39-none-manylinux_2_21_aarch64
  py39-none-manylinux_2_20_aarch64
  py39-none-manylinux_2_19_aarch64
  py39-none-manylinux_2_18_aarch64
  py39-none-manylinux_2_17_aarch64
  py39-none-manylinux2014_aarch64
  py39-none-linux_aarch64
  py3-none-manylinux_2_31_aarch64
  py3-none-manylinux_2_30_aarch64
  py3-none-manylinux_2_29_aarch64
  py3-none-manylinux_2_28_aarch64
  py3-none-manylinux_2_27_aarch64
  py3-none-manylinux_2_26_aarch64
  py3-none-manylinux_2_25_aarch64
  py3-none-manylinux_2_24_aarch64
  py3-none-manylinux_2_23_aarch64
  py3-none-manylinux_2_22_aarch64
  py3-none-manylinux_2_21_aarch64
  py3-none-manylinux_2_20_aarch64
  py3-none-manylinux_2_19_aarch64
  py3-none-manylinux_2_18_aarch64
  py3-none-manylinux_2_17_aarch64
  py3-none-manylinux2014_aarch64
  py3-none-linux_aarch64
  py38-none-manylinux_2_31_aarch64
  py38-none-manylinux_2_30_aarch64
  py38-none-manylinux_2_29_aarch64
  py38-none-manylinux_2_28_aarch64
  py38-none-manylinux_2_27_aarch64
  py38-none-manylinux_2_26_aarch64
  py38-none-manylinux_2_25_aarch64
  py38-none-manylinux_2_24_aarch64
  py38-none-manylinux_2_23_aarch64
  py38-none-manylinux_2_22_aarch64
  py38-none-manylinux_2_21_aarch64
  py38-none-manylinux_2_20_aarch64
  py38-none-manylinux_2_19_aarch64
  py38-none-manylinux_2_18_aarch64
  py38-none-manylinux_2_17_aarch64
  py38-none-manylinux2014_aarch64
  py38-none-linux_aarch64
  py37-none-manylinux_2_31_aarch64
  py37-none-manylinux_2_30_aarch64
  py37-none-manylinux_2_29_aarch64
  py37-none-manylinux_2_28_aarch64
  py37-none-manylinux_2_27_aarch64
  py37-none-manylinux_2_26_aarch64
  py37-none-manylinux_2_25_aarch64
  py37-none-manylinux_2_24_aarch64
  py37-none-manylinux_2_23_aarch64
  py37-none-manylinux_2_22_aarch64
  py37-none-manylinux_2_21_aarch64
  py37-none-manylinux_2_20_aarch64
  py37-none-manylinux_2_19_aarch64
  py37-none-manylinux_2_18_aarch64
  py37-none-manylinux_2_17_aarch64
  py37-none-manylinux2014_aarch64
  py37-none-linux_aarch64
  py36-none-manylinux_2_31_aarch64
  py36-none-manylinux_2_30_aarch64
  py36-none-manylinux_2_29_aarch64
  py36-none-manylinux_2_28_aarch64
  py36-none-manylinux_2_27_aarch64
  py36-none-manylinux_2_26_aarch64
  py36-none-manylinux_2_25_aarch64
  py36-none-manylinux_2_24_aarch64
  py36-none-manylinux_2_23_aarch64
  py36-none-manylinux_2_22_aarch64
  py36-none-manylinux_2_21_aarch64
  py36-none-manylinux_2_20_aarch64
  py36-none-manylinux_2_19_aarch64
  py36-none-manylinux_2_18_aarch64
  py36-none-manylinux_2_17_aarch64
  py36-none-manylinux2014_aarch64
  py36-none-linux_aarch64
  py35-none-manylinux_2_31_aarch64
  py35-none-manylinux_2_30_aarch64
  py35-none-manylinux_2_29_aarch64
  py35-none-manylinux_2_28_aarch64
  py35-none-manylinux_2_27_aarch64
  py35-none-manylinux_2_26_aarch64
  py35-none-manylinux_2_25_aarch64
  py35-none-manylinux_2_24_aarch64
  py35-none-manylinux_2_23_aarch64
  py35-none-manylinux_2_22_aarch64
  py35-none-manylinux_2_21_aarch64
  py35-none-manylinux_2_20_aarch64
  py35-none-manylinux_2_19_aarch64
  py35-none-manylinux_2_18_aarch64
  py35-none-manylinux_2_17_aarch64
  py35-none-manylinux2014_aarch64
  py35-none-linux_aarch64
  py34-none-manylinux_2_31_aarch64
  py34-none-manylinux_2_30_aarch64
  py34-none-manylinux_2_29_aarch64
  py34-none-manylinux_2_28_aarch64
  py34-none-manylinux_2_27_aarch64
  py34-none-manylinux_2_26_aarch64
  py34-none-manylinux_2_25_aarch64
  py34-none-manylinux_2_24_aarch64
  py34-none-manylinux_2_23_aarch64
  py34-none-manylinux_2_22_aarch64
  py34-none-manylinux_2_21_aarch64
  py34-none-manylinux_2_20_aarch64
  py34-none-manylinux_2_19_aarch64
  py34-none-manylinux_2_18_aarch64
  py34-none-manylinux_2_17_aarch64
  py34-none-manylinux2014_aarch64
  py34-none-linux_aarch64
  py33-none-manylinux_2_31_aarch64
  py33-none-manylinux_2_30_aarch64
  py33-none-manylinux_2_29_aarch64
  py33-none-manylinux_2_28_aarch64
  py33-none-manylinux_2_27_aarch64
  py33-none-manylinux_2_26_aarch64
  py33-none-manylinux_2_25_aarch64
  py33-none-manylinux_2_24_aarch64
  py33-none-manylinux_2_23_aarch64
  py33-none-manylinux_2_22_aarch64
  py33-none-manylinux_2_21_aarch64
  py33-none-manylinux_2_20_aarch64
  py33-none-manylinux_2_19_aarch64
  py33-none-manylinux_2_18_aarch64
  py33-none-manylinux_2_17_aarch64
  py33-none-manylinux2014_aarch64
  py33-none-linux_aarch64
  py32-none-manylinux_2_31_aarch64
  py32-none-manylinux_2_30_aarch64
  py32-none-manylinux_2_29_aarch64
  py32-none-manylinux_2_28_aarch64
  py32-none-manylinux_2_27_aarch64
  py32-none-manylinux_2_26_aarch64
  py32-none-manylinux_2_25_aarch64
  py32-none-manylinux_2_24_aarch64
  py32-none-manylinux_2_23_aarch64
  py32-none-manylinux_2_22_aarch64
  py32-none-manylinux_2_21_aarch64
  py32-none-manylinux_2_20_aarch64
  py32-none-manylinux_2_19_aarch64
  py32-none-manylinux_2_18_aarch64
  py32-none-manylinux_2_17_aarch64
  py32-none-manylinux2014_aarch64
  py32-none-linux_aarch64
  py31-none-manylinux_2_31_aarch64
  py31-none-manylinux_2_30_aarch64
  py31-none-manylinux_2_29_aarch64
  py31-none-manylinux_2_28_aarch64
  py31-none-manylinux_2_27_aarch64
  py31-none-manylinux_2_26_aarch64
  py31-none-manylinux_2_25_aarch64
  py31-none-manylinux_2_24_aarch64
  py31-none-manylinux_2_23_aarch64
  py31-none-manylinux_2_22_aarch64
  py31-none-manylinux_2_21_aarch64
  py31-none-manylinux_2_20_aarch64
  py31-none-manylinux_2_19_aarch64
  py31-none-manylinux_2_18_aarch64
  py31-none-manylinux_2_17_aarch64
  py31-none-manylinux2014_aarch64
  py31-none-linux_aarch64
  py30-none-manylinux_2_31_aarch64
  py30-none-manylinux_2_30_aarch64
  py30-none-manylinux_2_29_aarch64
  py30-none-manylinux_2_28_aarch64
  py30-none-manylinux_2_27_aarch64
  py30-none-manylinux_2_26_aarch64
  py30-none-manylinux_2_25_aarch64
  py30-none-manylinux_2_24_aarch64
  py30-none-manylinux_2_23_aarch64
  py30-none-manylinux_2_22_aarch64
  py30-none-manylinux_2_21_aarch64
  py30-none-manylinux_2_20_aarch64
  py30-none-manylinux_2_19_aarch64
  py30-none-manylinux_2_18_aarch64
  py30-none-manylinux_2_17_aarch64
  py30-none-manylinux2014_aarch64
  py30-none-linux_aarch64
  cp39-none-any
  py39-none-any
  py3-none-any
  py38-none-any
  py37-none-any
  py36-none-any
  py35-none-any
  py34-none-any
  py33-none-any
  py32-none-any
  py31-none-any
  py30-none-any
```

**Comment by jackokring** [comment]
```
(venv) jackokring@penguin:~/www$ pip install chafa.py
Collecting chafa.py
  Downloading chafa.py-1.1.0.tar.gz (3.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 2.9 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: chafa.py
  Building wheel for chafa.py (pyproject.toml) ... done
  Created wheel for chafa.py: filename=chafa.py-1.1.0-cp39-cp39-manylinux_2_31_aarch64.whl size=36252 sha256=cda995ac80babce435cd2d103fccf84ddc5624f6389f4328f80cee0f3c78723a
  Stored in directory: /home/jackokring/.cache/pip/wheels/77/23/b3/458a17a819bbe6cbcdd1c987c4922c793d14239813effec99d
Successfully built chafa.py
Installing collected packages: chafa.py
Successfully installed chafa.py-1.1.0
```

**Comment by GuardKenzie** [comment]
Should I mark this as resolved?

Looks like you are on Linux ARM. There are no wheels for that architecture yet but I'll take a look at getting those built with GitHub actions.
